title: OptaPlanner
description: OptaPlanner optimizes business resource usage. It is a lightweight, embeddable, open source planning engine, written in 100% Java.
keywords: metaheuristic, heuristic, constraint satisfaction, constraint programming, NP-complete, NP-hard, optimization, planning, scheduling, java, open source, software, library, solver, tabu search, simulated annealing, pareto
canonicalBaseUrl: http://www.optaplanner.org

# jbossorg_bootstrap_css: http://static.jboss.org/theme/css/bootstrap/2.1.0.0.0/bootstrap-community.css
# jbossorg_bootstrap_js: http://static.jboss.org/theme/js/libs/bootstrap/2.1.0.0.0/bootstrap-community.js

profiles:
  development:
    developmentMode: true
  production:
    developmentMode: false
