encoding: UTF-8
lang: en
title: OptaPlanner
description: OptaPlanner optimizes business resource usage. It is a lightweight, embeddable, open source planning engine, written in 100% Java.
keywords: metaheuristic, heuristic, constraint satisfaction, constraint programming, operations research, NP-complete, NP-hard, optimization, planning, scheduling, java, open source, software, library, solver, tabu search, simulated annealing, pareto
canonicalBaseUrl: http://www.optaplanner.org

googleAnalyticsId: UA-39485370-1
googleTagManagerId: GTM-NJWS5L
googleTagManagerChannel: OptaPlanner
googleWebmasterToolsVerificationId: 7maFZB6ae01GhEGx5Go9FO7fnTHZhY--_9rkLLawXbk
disqus: optaplanner
disqus_generate_id: true

asciidoctor:
  :safe: safe
  :attributes:
    imagesdir: ''

profiles:
  development:
    developmentMode: true
  production:
    developmentMode: false
    base_url: http://www.optaplanner.org
